server:
  port: 8001
spring:
   application:
    name: '@artifactId@'

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://admin:123456@eureka7001.com:7001/eureka/,http://admin:123456@eureka7002.com:7002/eureka/